name: dossier
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.7
  cupertino_icons: ^1.0.2
  flutter_acrylic: ^1.1.3
  get:
  animations: ^2.0.2
  badges: ^3.1.2
  change_app_package_name: ^1.0.0
  dart_amqp: ^0.2.1
  dio: ^5.3.3
  extended_image: ^8.1.1
  fl_chart: ^0.45.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  hive: ^2.0.5
  hive_flutter: null
  material_design_icons_flutter: ^5.0.6595
  palette_generator: ^0.3.3
  persistent_bottom_nav_bar: ^5.0.2
  syncfusion_flutter_calendar: ^23.1.40
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg